name: Wes Harrison AI
favicon: null
layout_spectrum: 0.5236794445663691
typography_spectrum: 0.7508638487197459
title: Site Built Using AI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242424'
    - '#555555'
    - '#757575'
    - '#939393'
    - '#c8c8c8'
  brandStrength: 0.05055988812819123
  lightness: 0.665782438358292
  saturation: 0.8737730854190886
  rhythmicContrast: 0.1487623166758567
purpose: []
